export const LOCALIDADES = [
  "Agost",
  "Agres",
  "Aigües",
  "Alacant/Alicante",
  "Albatera",
  "Alcalalí",
  "Alcoi/Alcoy",
  "Alcoleja",
  "Alcosser",
  "Alfafara",
  "Alfàs del Pi, l'",
  "Algorfa",
  "Algueña",
  "Almoradí",
  "Almudaina",
  "Alqueria d'Asnar, l'",
  "Altea",
  "Aspe",
  "Atzúbia, l'",
  "Balones",
  "Banyeres de Mariola",
  "Benasau",
  "Beneixama",
  "Benejúzar",
  "Benferri",
  "Beniarbeig",
  "Beniardà",
  "Beniarrés",
  "Benidoleig",
  "Benidorm",
  "Benifallim",
  "Benifato",
  "Benigembla",
  "Benijófar",
  "Benilloba",
  "Benillup",
  "Benimantell",
  "Benimarfull",
  "Benimassot",
  "Benimeli",
  "Benissa",
  "Biar",
  "Bigastro",
  "Bolulla",
  "Busot",
  "Callosa de Segura",
  "Callosa d'en Sarrià",
  "Calp",
  "Camp de Mirra, el/Campo de Mirra",
  "Campello, el",
  "Cañada",
  "Castalla",
  "Castell de Castells",
  "Castell de Guadalest, el",
  "Catral",
  "Cocentaina",
  "Confrides",
  "Cox",
  "Crevillent",
  "Daya Nueva",
  "Daya Vieja",
  "Dénia",
  "Dolores",
  "Elda",
  "Elx/Elche",
  "Fageca",
  "Famorca",
  "Finestrat",
  "Fondó de les Neus, el/Hondón de las Nieves",
  "Formentera del Segura",
  "Gaianes",
  "Gata de Gorgos",
  "Gorga",
  "Granja de Rocamora",
  "Guardamar del Segura",
  "Hondón de los Frailes",
  "Ibi",
  "Jacarilla",
  "Llíber",
  "Millena",
  "Monforte del Cid",
  "Monòver/Monóvar",
  "Montesinos, Los",
  "Murla",
  "Muro de Alcoy",
  "Mutxamel",
  "Novelda",
  "Nucia, la",
  "Ondara",
  "Onil",
  "Orba",
  "Orihuela",
  "Orxa, l'/Lorcha",
  "Orxeta",
  "Parcent",
  "Pedreguer",
  "Pego",
  "Penàguila",
  "Petrer",
  "Pilar de la Horadada",
  "Pinós, el/Pinoso",
  "Planes",
  "Poble Nou de Benitatxell, el/Benitachell",
  "Poblets, els",
  "Polop",
  "Quatretondeta",
  "Rafal",
  "Ràfol d'Almúnia, el",
  "Redován",
  "Relleu",
  "Rojales",
  "Romana, la",
  "Sagra",
  "Salinas",
  "San Fulgencio",
  "San Isidro",
  "San Miguel de Salinas",
  "Sanet y Negrals",
  "Sant Joan d'Alacant",
  "Sant Vicent del Raspeig/San Vicente del Raspeig",
  "Santa Pola",
  "Sax",
  "Sella",
  "Senija",
  "Tàrbena",
  "Teulada",
  "Tibi",
  "Tollos",
  "Tormos",
  "Torre de les Maçanes, la/Torremanzanas",
  "Torrevieja",
  "Vall d'Alcalà, la",
  "Vall de Gallinera, la",
  "Vall de Laguar, la",
  "Vall d'Ebo, la",
  "Verger, el",
  "Vila Joiosa, la/Villajoyosa",
  "Villena",
  "Xàbia/Jávea",
  "Xaló",
  "Xixona/Jijona",
  "Aín",
  "Albocàsser",
  "Alcalà de Xivert",
  "Alcora, l'",
  "Alcudia de Veo",
  "Alfondeguilla",
  "Algimia de Almonacid",
  "Almassora",
  "Almedíjar",
  "Almenara",
  "Alqueries, les/Alquerías del Niño Perdido",
  "Altura",
  "Arañuel",
  "Ares del Maestrat",
  "Argelita",
  "Artana",
  "Atzeneta del Maestrat",
  "Ayódar",
  "Azuébar",
  "Barracas",
  "Bejís",
  "Benafer",
  "Benafigos",
  "Benassal",
  "Benicarló",
  "Benicàssim/Benicasim",
  "Benlloc",
  "Betxí",
  "Borriana/Burriana",
  "Borriol",
  "Cabanes",
  "Càlig",
  "Canet lo Roig",
  "Castell de Cabres",
  "Castellfort",
  "Castellnovo",
  "Castelló de la Plana",
  "Castillo de Villamalefa",
  "Catí",
  "Caudiel",
  "Cervera del Maestre",
  "Chilches/Xilxes",
  "Chóvar",
  "Cinctorres",
  "Cirat",
  "Cortes de Arenoso",
  "Costur",
  "Coves de Vinromà, les",
  "Culla",
  "Eslida",
  "Espadilla",
  "Fanzara",
  "Figueroles",
  "Forcall",
  "Fuente la Reina",
  "Fuentes de Ayódar",
  "Gaibiel",
  "Geldo",
  "Herbers",
  "Higueras",
  "Jana, la",
  "Jérica",
  "Llosa, la",
  "Llucena/Lucena del Cid",
  "Ludiente",
  "Mata de Morella, la",
  "Matet",
  "Moncofa",
  "Montán",
  "Montanejos",
  "Morella",
  "Navajas",
  "Nules",
  "Olocau del Rey",
  "Onda",
  "Orpesa/Oropesa del Mar",
  "Palanques",
  "Pavías",
  "Peníscola/Peñíscola",
  "Pina de Montalgrao",
  "Pobla de Benifassà, la",
  "Pobla Tornesa, la",
  "Portell de Morella",
  "Puebla de Arenoso",
  "Ribesalbes",
  "Rossell",
  "Sacañet",
  "Salzadella, la",
  "San Rafael del Río",
  "Sant Joan de Moró",
  "Sant Jordi/San Jorge",
  "Sant Mateu",
  "Santa Magdalena de Pulpis",
  "Segorbe",
  "Serratella, la",
  "Sierra Engarcerán",
  "Soneja",
  "Sot de Ferrer",
  "Suera/Sueras",
  "Tales",
  "Teresa",
  "Tírig",
  "Todolella",
  "Toga",
  "Torás",
  "Toro, El",
  "Torralba del Pinar",
  "Torre d'en Besora, la",
  "Torre d'en Doménec, la",
  "Torreblanca",
  "Torrechiva",
  "Traiguera",
  "Useres, les/Useras",
  "Vall d'Alba",
  "Vall de Almonacid",
  "Vall d'Uixó, la",
  "Vallat",
  "Vallibona",
  "Vilafamés",
  "Vilafranca/Villafranca del Cid",
  "Vilanova d'Alcolea",
  "Vilar de Canes",
  "Vila-real",
  "Vilavella, la",
  "Villahermosa del Río",
  "Villamalur",
  "Villanueva de Viver",
  "Villores",
  "Vinaròs",
  "Vistabella del Maestrat",
  "Viver",
  "Xert",
  "Xodos/Chodos",
  "Zorita del Maestrazgo",
  "Zucaina",
  "Ademuz",
  "Ador",
  "Agullent",
  "Aielo de Malferit",
  "Aielo de Rugat",
  "Alaquàs",
  "Albaida",
  "Albal",
  "Albalat de la Ribera",
  "Albalat dels Sorells",
  "Albalat dels Tarongers",
  "Alberic",
  "Alborache",
  "Alboraia/Alboraya",
  "Albuixech",
  "Alcàntera de Xúquer",
  "Alcàsser",
  "Alcublas",
  "Alcúdia de Crespins, l'",
  "Alcúdia, l'",
  "Aldaia",
  "Alfafar",
  "Alfara de la Baronia",
  "Alfara del Patriarca",
  "Alfarp",
  "Alfarrasí",
  "Alfauir",
  "Algar de Palancia",
  "Algemesí",
  "Algímia d'Alfara",
  "Alginet",
  "Almàssera",
  "Almiserà",
  "Almoines",
  "Almussafes",
  "Alpuente",
  "Alqueria de la Comtessa, l'",
  "Alzira",
  "Andilla",
  "Anna",
  "Antella",
  "Aras de los Olmos",
  "Atzeneta d'Albaida",
  "Ayora",
  "Barx",
  "Barxeta",
  "Bèlgida",
  "Bellreguard",
  "Bellús",
  "Benagéber",
  "Benaguasil",
  "Benavites",
  "Beneixida",
  "Benetússer",
  "Beniarjó",
  "Beniatjar",
  "Benicolet",
  "Benicull de Xúquer",
  "Benifaió",
  "Benifairó de la Valldigna",
  "Benifairó de les Valls",
  "Beniflá",
  "Benigànim",
  "Benimodo",
  "Benimuslem",
  "Beniparrell",
  "Benirredrà",
  "Benissanó",
  "Benissoda",
  "Benissuera",
  "Bétera",
  "Bicorp",
  "Bocairent",
  "Bolbaite",
  "Bonrepòs i Mirambell",
  "Bufali",
  "Bugarra",
  "Buñol",
  "Burjassot",
  "Calles",
  "Camporrobles",
  "Canals",
  "Canet d'En Berenguer",
  "Carcaixent",
  "Càrcer",
  "Carlet",
  "Carrícola",
  "Casas Altas",
  "Casas Bajas",
  "Casinos",
  "Castelló",
  "Castelló de Rugat",
  "Castellonet de la Conquesta",
  "Castielfabib",
  "Catadau",
  "Catarroja",
  "Caudete de las Fuentes",
  "Cerdà",
  "Chella",
  "Chelva",
  "Chera",
  "Cheste",
  "Chiva",
  "Chulilla",
  "Cofrentes",
  "Corbera",
  "Cortes de Pallás",
  "Cotes",
  "Cullera",
  "Daimús",
  "Domeño",
  "Dos Aguas",
  "Eliana, l'",
  "Emperador",
  "Enguera",
  "Énova, l'",
  "Estivella",
  "Estubeny",
  "Faura",
  "Favara",
  "Foios",
  "Font de la Figuera, la",
  "Font d'en Carròs, la",
  "Fontanars dels Alforins",
  "Fortaleny",
  "Fuenterrobles",
  "Gandia",
  "Gátova",
  "Gavarda",
  "Genovés, el",
  "Gestalgar",
  "Gilet",
  "Godella",
  "Godelleta",
  "Granja de la Costera, la",
  "Guadasséquies",
  "Guadassuar",
  "Guardamar de la Safor",
  "Higueruelas",
  "Jalance",
  "Jarafuel",
  "Llanera de Ranes",
  "Llaurí",
  "Llíria",
  "Llocnou de la Corona",
  "Llocnou de Sant Jeroni",
  "Llocnou d'En Fenollet",
  "Llombai",
  "Llosa de Ranes, la",
  "Llutxent",
  "Loriguilla",
  "Losa del Obispo",
  "Macastre",
  "Manises",
  "Manuel",
  "Marines",
  "Massalavés",
  "Massalfassar",
  "Massamagrell",
  "Massanassa",
  "Meliana",
  "Millares",
  "Miramar",
  "Mislata",
  "Moixent/Mogente",
  "Moncada",
  "Montaverner",
  "Montesa",
  "Montitxelvo/Montichelvo",
  "Montroi/Montroy",
  "Montserrat",
  "Museros",
  "Nàquera/Náquera",
  "Navarrés",
  "Novetlè/Novelé",
  "Oliva",
  "Olleria, l'",
  "Olocau",
  "Ontinyent",
  "Otos",
  "Paiporta",
  "Palma de Gandía",
  "Palmera",
  "Palomar, el",
  "Paterna",
  "Pedralba",
  "Petrés",
  "Picanya",
  "Picassent",
  "Piles",
  "Pinet",
  "Pobla de Farnals, la",
  "Pobla de Vallbona, la",
  "Pobla del Duc, la",
  "Pobla Llarga, la",
  "Polinyà de Xúquer",
  "Potries",
  "Puçol",
  "Puebla de San Miguel",
  "Puig de Santa Maria, el",
  "Quart de les Valls",
  "Quart de Poblet",
  "Quartell",
  "Quatretonda",
  "Quesa",
  "Rafelbunyol",
  "Rafelcofer",
  "Rafelguaraf",
  "Ráfol de Salem",
  "Real",
  "Real de Gandia, el",
  "Requena",
  "Riba-roja de Túria",
  "Riola",
  "Rocafort",
  "Rotglà i Corberà",
  "Ròtova",
  "Rugat",
  "Sagunt/Sagunto",
  "Salem",
  "San Antonio de Benagéber",
  "Sant Joanet",
  "Sedaví",
  "Segart",
  "Sellent",
  "Sempere",
  "Senyera",
  "Serra",
  "Siete Aguas",
  "Silla",
  "Simat de la Valldigna",
  "Sinarcas",
  "Sollana",
  "Sot de Chera",
  "Sueca",
  "Sumacàrcer",
  "Tavernes Blanques",
  "Tavernes de la Valldigna",
  "Teresa de Cofrentes",
  "Terrateig",
  "Titaguas",
  "Torrebaja",
  "Torrella",
  "Torrent",
  "Torres Torres",
  "Tous",
  "Tuéjar",
  "Turís",
  "Utiel",
  "València",
  "Vallada",
  "Vallanca",
  "Vallés",
  "Venta del Moro",
  "Vilallonga/Villalonga",
  "Vilamarxant",
  "Villar del Arzobispo",
  "Villargordo del Cabriel",
  "Vinalesa",
  "Xàtiva",
  "Xeraco",
  "Xeresa",
  "Xirivella",
  "Yátova",
  "Yesa, La",
  "Zarra",
];
